spring.application.name=userservice-merezh

spring.datasource.url=jdbc:postgresql://postgres-userservice:5432/userservice-merezh
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
